version: '3'

services:
  app:
    container_name: service
    build: .
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - backend
    command: pnpm run start
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  app:
networks:
  backend:
    driver: bridge
