version: '3'

services:
  app:
    container_name: service
    depends_on:
      - dev-database
    build: .
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - backend
    command: pnpm run start
    volumes:
      - .:/app
      - /app/node_modules
  dev-database:
    container_name: dev-database
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27018:27017
    expose:
      - 27018
    volumes:
      - dev-database:/data/db
    restart: unless-stopped
    networks:
      - backend
  dev-rabbitmq:
    container_name: dev-rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - dev-rabbitmq:/data/rabbitmq
    restart: unless-stopped

volumes:
  app:
  dev-database:
  dev-rabbitmq:
networks:
  backend:
    driver: bridge
