name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@vivant-grupa'

    - name: Install dependencies
      run: pnpm install

    - name: Run Linter
      run: pnpm run lint

    - name: Run Tests
      run: pnpm run test
